### ISSUE TITLE
同学你好

### ISSUE THREAD

**Issue by wuhuzi** [HHHendricks/bookshop#1]
同学你好，skumra/robotic-grasping 的代码你跑起来了嘛？尤其是 python run_grasp_generator.py

**Comment by HHHendricks** [comment]
我只运行了推理模块的部分，也就只是预测抓取矩形的模块。后面和机器人模块的代码还没有运行，因为缺少机器人相关的硬件，所以应该帮不了你了...




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "HHHendricks/bookshop"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年12月1日(星期二) 晚上8:29
收件人:&nbsp;"HHHendricks/bookshop"<bookshop@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;[HHHendricks/bookshop] 同学你好 (#1)





 
同学你好，skumra/robotic-grasping 的代码你跑起来了嘛？尤其是 python run_grasp_generator.py

**Comment by wuhuzi** [comment]
谢谢你的回复 ，Best wish. 顺颂商祺
